echo Mise à jour du serveur...
sudo apt-get update
echo Installation de pip...
sudo apt install pip -y
echo Installation des packages nécessaires...
pip install -r auto_bot/requirements.txt
touch cronlog.log

echo Installation finie
